name = "la-volotte"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-11-26"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true